# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 54287ced86628c01c5419612075e9c67c3c921bbe8809ce4c9714b931e2cca3fe47e43d1a847ca57bca420a2024c99dda70fb318d41a906b23b29439f986dae5

test:
  secret_key_base: 533daefa17638814ac320e4b00c829f1aae73a9edd9ebbc8e545c55b8f385fc1eefb8373a7d38bf0447b4a5a93c010392a573add4f5d2fb936b6b4dbd9801dc2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
